services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:  wallet_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/test-wallet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=P4ssword!
    depends_on:
      - database

  database:
    image: postgres:17.2
    container_name: wallet_db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=test-wallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    volumes:
      - wallet_db:/var/lib/postgresql/data

volumes:
  wallet_db:
