spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/test-wallet}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 600000
      maximum-pool-size: 32
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        id:
          new_generator_mappings: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
    contexts:
      - dev
      - test
springdoc:
  swagger-ui.path: /swagger-ui.html
